// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOPOc8xYokQfgTTUKskdowhImNkQUSAe4',
    appId: '1:191735267327:web:1d5e443b9cd556d5b6b1ca',
    messagingSenderId: '191735267327',
    projectId: 'auto-spare-api',
    authDomain: 'auto-spare-api.firebaseapp.com',
    storageBucket: 'auto-spare-api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCud1_wSpG-YE88NXAhvfStPxUIsMfSbj4',
    appId: '1:191735267327:android:37553eb3790d7cbdb6b1ca',
    messagingSenderId: '191735267327',
    projectId: 'auto-spare-api',
    storageBucket: 'auto-spare-api.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOPOc8xYokQfgTTUKskdowhImNkQUSAe4',
    appId: '1:191735267327:web:2b9fc4d0ffc9141cb6b1ca',
    messagingSenderId: '191735267327',
    projectId: 'auto-spare-api',
    authDomain: 'auto-spare-api.firebaseapp.com',
    storageBucket: 'auto-spare-api.firebasestorage.app',
  );
}
